CREATE TABLE "EMPLOYEE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	"DOB" date,
	"CONTACT" text NOT NULL,
	"EMAIL" text,
	"SEX" integer NOT NULL,
	"JOINING_DATE" date,
	"END_DATE" date,
	"NID_NUMBER" text,
	"IMAGE_URL" text,
	"PASSWORD" text NOT NULL,
	"LAST_LOGIN" timestamp,
	"ON_VACATION" boolean DEFAULT false NOT NULL,
	"ACTIVE_STATUS" boolean DEFAULT true NOT NULL,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp,
	CONSTRAINT "EMPLOYEE_EMAIL_unique" UNIQUE("EMAIL"),
	CONSTRAINT "EMPLOYEE_NID_NUMBER_unique" UNIQUE("NID_NUMBER")
);
--> statement-breakpoint
CREATE TABLE "EMPLOYEE_ADDRESS" (
	"EMPLOYEE_ID" integer PRIMARY KEY NOT NULL,
	"ADDRESS_LINE_1" text NOT NULL,
	"ADDRESS_LINE_2" text NOT NULL,
	"CITY" text,
	"STATE" text,
	"POSTAL_CODE" text,
	"COUNTRY" text,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp
);
--> statement-breakpoint
CREATE TABLE "EMPLOYEE_ROLE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	CONSTRAINT "EMPLOYEE_ROLE_NAME_unique" UNIQUE("NAME")
);
--> statement-breakpoint
CREATE TABLE "EMPLOYEE_ROLE_ASSIGNMENT" (
	"EMPLOYEE_ID" integer NOT NULL,
	"EMPLOYEE_ROLE_ID" integer NOT NULL,
	CONSTRAINT "EMPLOYEE_ROLE_ASSIGNMENT_EMPLOYEE_ID_EMPLOYEE_ROLE_ID_pk" PRIMARY KEY("EMPLOYEE_ID","EMPLOYEE_ROLE_ID")
);
--> statement-breakpoint
CREATE TABLE "SALARY_SHEET" (
	"ID" serial PRIMARY KEY NOT NULL,
	"EMPLOYEE_ID" integer NOT NULL,
	"SALARY_AMOUNT" numeric(12, 2) NOT NULL,
	"SALARY_START_DATE" date,
	"SALARY_END_DATE" date,
	"ACTIVE_STATUS" boolean DEFAULT true NOT NULL,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp
);
--> statement-breakpoint
CREATE TABLE "CUSTOMER" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text,
	"CONTACT" text,
	"EMAIL" text,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp,
	CONSTRAINT "CUSTOMER_EMAIL_unique" UNIQUE("EMAIL")
);
--> statement-breakpoint
CREATE TABLE "MEMBER" (
	"customer_id" integer PRIMARY KEY NOT NULL,
	"membership_number" text,
	"points" numeric(12, 2),
	"discount" numeric(12, 2),
	"discount_type_id" integer,
	"dob" date,
	"card_issue_date" date NOT NULL,
	"membership_expiry_date" date,
	"active_status" boolean DEFAULT true NOT NULL,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp,
	CONSTRAINT "MEMBER_membership_number_unique" UNIQUE("membership_number")
);
--> statement-breakpoint
CREATE TABLE "MEMBER_ADDRESS" (
	"ID" serial PRIMARY KEY NOT NULL,
	"CUSTOMER_ID" integer NOT NULL,
	"ADDRESS_TYPE_ID" integer,
	"ADDRESS_LINE_1" text NOT NULL,
	"ADDRESS_LINE_2" text NOT NULL,
	"CITY" text,
	"STATE" text,
	"POSTAL_CODE" text,
	"COUNTRY" text,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp
);
--> statement-breakpoint
CREATE TABLE "ADDRESS_TYPE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	CONSTRAINT "ADDRESS_TYPE_NAME_unique" UNIQUE("NAME")
);
--> statement-breakpoint
CREATE TABLE "DISCOUNT_TYPE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	CONSTRAINT "DISCOUNT_TYPE_NAME_unique" UNIQUE("NAME")
);
--> statement-breakpoint
CREATE TABLE "FOOD_CATEGORY" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	"ACTIVE_STATUS" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FOOD_CATEGORY_RELATION_MENU" (
	"FOOD_MENU_ID" integer NOT NULL,
	"FOOD_CATEGORY_ID" integer NOT NULL,
	CONSTRAINT "FOOD_CATEGORY_RELATION_MENU_FOOD_MENU_ID_FOOD_CATEGORY_ID_pk" PRIMARY KEY("FOOD_MENU_ID","FOOD_CATEGORY_ID")
);
--> statement-breakpoint
CREATE TABLE "FOOD_MENU" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text,
	"DESCRIPTION" text,
	"IMAGE_URL" text,
	"PREPARATION_TIME" interval,
	"PRICE" numeric(12, 2),
	"ACTIVE_STATUS" boolean DEFAULT true NOT NULL,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp
);
--> statement-breakpoint
CREATE TABLE "CUSTOMER_ORDER" (
	"ID" serial PRIMARY KEY NOT NULL,
	"CUSTOMER_ID" integer,
	"ORDER_NUMBER" text NOT NULL,
	"EMPLOYEE_ID" integer,
	"ORDER_TIME" timestamp,
	"SUBTOTAL" double precision,
	"DISCOUNT" double precision,
	"VAT" double precision,
	"NET_TOTAL" double precision,
	"ORDER_STATUS_ID" integer,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp,
	CONSTRAINT "CUSTOMER_ORDER_ORDER_NUMBER_unique" UNIQUE("ORDER_NUMBER")
);
--> statement-breakpoint
CREATE TABLE "ORDER_DETAIL" (
	"ID" serial PRIMARY KEY NOT NULL,
	"CUSTOMER_ORDER_ID" integer NOT NULL,
	"FOOD_MENU_ID" integer NOT NULL,
	"ORDER_TYPE_ID" integer NOT NULL,
	"PROMOTION_ID" integer,
	"UNIT_PRICE" double precision NOT NULL,
	"QUANTITY" integer NOT NULL,
	"DISCOUNT_AMOUNT" double precision,
	"LINE_TOTAL" double precision,
	"FINAL_AMOUNT" double precision NOT NULL,
	"ACTIVE_STATUS" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ORDER_STATUS" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	CONSTRAINT "ORDER_STATUS_NAME_unique" UNIQUE("NAME")
);
--> statement-breakpoint
CREATE TABLE "ORDER_STATUS_LOG" (
	"ID" serial PRIMARY KEY NOT NULL,
	"CUSTOMER_ORDER_ID" integer NOT NULL,
	"ORDER_STATUS_ID" integer NOT NULL,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp,
	"NOTE" varchar(500)
);
--> statement-breakpoint
CREATE TABLE "ORDER_TYPE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	CONSTRAINT "ORDER_TYPE_NAME_unique" UNIQUE("NAME")
);
--> statement-breakpoint
CREATE TABLE "PAYMENT" (
	"ID" serial PRIMARY KEY NOT NULL,
	"CUSTOMER_ORDER_ID" integer NOT NULL,
	"PAYMENT_TYPE_ID" integer NOT NULL,
	"TRANSACTION_ID" text,
	"AMOUNT" double precision NOT NULL,
	"CURRENT_PAYMENT_STATUS_ID" integer NOT NULL,
	"PAYMENT_TIME" timestamp,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp,
	CONSTRAINT "PAYMENT_TRANSACTION_ID_unique" UNIQUE("TRANSACTION_ID")
);
--> statement-breakpoint
CREATE TABLE "PAYMENT_STATUS" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PAYMENT_STATUS_LOG" (
	"ID" serial PRIMARY KEY NOT NULL,
	"PAYMENT_ID" integer NOT NULL,
	"PAYMENT_STATUS_ID" integer NOT NULL,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp
);
--> statement-breakpoint
CREATE TABLE "PAYMENT_TYPE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PROMOTION" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	"DESCRIPTION" text,
	"PROMOTION_TYPE_ID" integer,
	"START_TIME" timestamp,
	"END_TIME" timestamp,
	"IS_PERMANENT" boolean,
	"ACTIVE_STATUS" boolean DEFAULT true NOT NULL,
	"CREATED_BY" integer,
	"CREATED_ON" timestamp,
	"UPDATED_BY" integer,
	"UPDATED_ON" timestamp
);
--> statement-breakpoint
CREATE TABLE "PROMOTION_TYPE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"NAME" text NOT NULL,
	CONSTRAINT "PROMOTION_TYPE_NAME_unique" UNIQUE("NAME")
);
--> statement-breakpoint
CREATE TABLE "PROMOTION_FOOD" (
	"PROMOTION_ID" integer NOT NULL,
	"FOOD_MENU_ID" integer NOT NULL,
	CONSTRAINT "PROMOTION_FOOD_PROMOTION_ID_FOOD_MENU_ID_pk" PRIMARY KEY("PROMOTION_ID","FOOD_MENU_ID")
);
--> statement-breakpoint
CREATE TABLE "DISCOUNT_RULE" (
	"PROMOTION_ID" integer PRIMARY KEY NOT NULL,
	"DISCOUNT_VALUE" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "BUY_X_GET_Y_RULE" (
	"PROMOTION_ID" integer PRIMARY KEY NOT NULL,
	"BUY_FOOD_ID" integer,
	"BUY_QUANTITY" integer NOT NULL,
	"FREE_FOOD_ID" integer,
	"FREE_FOOD_QUANTITY" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ORDER_TABLE_ASSIGNMENT" (
	"CUSTOMER_ORDER_ID" integer NOT NULL,
	"RESTAURANT_TABLE_ID" integer NOT NULL,
	CONSTRAINT "ORDER_TABLE_ASSIGNMENT_CUSTOMER_ORDER_ID_RESTAURANT_TABLE_ID_pk" PRIMARY KEY("CUSTOMER_ORDER_ID","RESTAURANT_TABLE_ID")
);
--> statement-breakpoint
CREATE TABLE "RESTAURANT_TABLE" (
	"ID" serial PRIMARY KEY NOT NULL,
	"CAPACITY" integer NOT NULL,
	"TABLE_NO" integer NOT NULL,
	"ACTIVE_STATUS" boolean DEFAULT true NOT NULL,
	CONSTRAINT "RESTAURANT_TABLE_TABLE_NO_unique" UNIQUE("TABLE_NO")
);
--> statement-breakpoint
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EMPLOYEE_ADDRESS" ADD CONSTRAINT "EMPLOYEE_ADDRESS_EMPLOYEE_ID_EMPLOYEE_ID_fk" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EMPLOYEE_ADDRESS" ADD CONSTRAINT "EMPLOYEE_ADDRESS_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EMPLOYEE_ADDRESS" ADD CONSTRAINT "EMPLOYEE_ADDRESS_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EMPLOYEE_ROLE_ASSIGNMENT" ADD CONSTRAINT "EMPLOYEE_ROLE_ASSIGNMENT_EMPLOYEE_ID_EMPLOYEE_ID_fk" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EMPLOYEE_ROLE_ASSIGNMENT" ADD CONSTRAINT "EMPLOYEE_ROLE_ASSIGNMENT_EMPLOYEE_ROLE_ID_EMPLOYEE_ROLE_ID_fk" FOREIGN KEY ("EMPLOYEE_ROLE_ID") REFERENCES "public"."EMPLOYEE_ROLE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "SALARY_SHEET" ADD CONSTRAINT "SALARY_SHEET_EMPLOYEE_ID_EMPLOYEE_ID_fk" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "SALARY_SHEET" ADD CONSTRAINT "SALARY_SHEET_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "SALARY_SHEET" ADD CONSTRAINT "SALARY_SHEET_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_customer_id_CUSTOMER_ID_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."CUSTOMER"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MEMBER_ADDRESS" ADD CONSTRAINT "MEMBER_ADDRESS_CUSTOMER_ID_CUSTOMER_ID_fk" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "public"."CUSTOMER"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MEMBER_ADDRESS" ADD CONSTRAINT "MEMBER_ADDRESS_ADDRESS_TYPE_ID_ADDRESS_TYPE_ID_fk" FOREIGN KEY ("ADDRESS_TYPE_ID") REFERENCES "public"."ADDRESS_TYPE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MEMBER_ADDRESS" ADD CONSTRAINT "MEMBER_ADDRESS_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "MEMBER_ADDRESS" ADD CONSTRAINT "MEMBER_ADDRESS_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FOOD_CATEGORY_RELATION_MENU" ADD CONSTRAINT "FOOD_CATEGORY_RELATION_MENU_FOOD_MENU_ID_FOOD_MENU_ID_fk" FOREIGN KEY ("FOOD_MENU_ID") REFERENCES "public"."FOOD_MENU"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FOOD_CATEGORY_RELATION_MENU" ADD CONSTRAINT "FOOD_CATEGORY_RELATION_MENU_FOOD_CATEGORY_ID_FOOD_CATEGORY_ID_fk" FOREIGN KEY ("FOOD_CATEGORY_ID") REFERENCES "public"."FOOD_CATEGORY"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FOOD_MENU" ADD CONSTRAINT "FOOD_MENU_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FOOD_MENU" ADD CONSTRAINT "FOOD_MENU_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUSTOMER_ORDER" ADD CONSTRAINT "CUSTOMER_ORDER_CUSTOMER_ID_CUSTOMER_ID_fk" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "public"."CUSTOMER"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUSTOMER_ORDER" ADD CONSTRAINT "CUSTOMER_ORDER_EMPLOYEE_ID_EMPLOYEE_ID_fk" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUSTOMER_ORDER" ADD CONSTRAINT "CUSTOMER_ORDER_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CUSTOMER_ORDER" ADD CONSTRAINT "CUSTOMER_ORDER_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_DETAIL" ADD CONSTRAINT "ORDER_DETAIL_CUSTOMER_ORDER_ID_CUSTOMER_ORDER_ID_fk" FOREIGN KEY ("CUSTOMER_ORDER_ID") REFERENCES "public"."CUSTOMER_ORDER"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_DETAIL" ADD CONSTRAINT "ORDER_DETAIL_FOOD_MENU_ID_FOOD_MENU_ID_fk" FOREIGN KEY ("FOOD_MENU_ID") REFERENCES "public"."FOOD_MENU"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_DETAIL" ADD CONSTRAINT "ORDER_DETAIL_ORDER_TYPE_ID_ORDER_TYPE_ID_fk" FOREIGN KEY ("ORDER_TYPE_ID") REFERENCES "public"."ORDER_TYPE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_DETAIL" ADD CONSTRAINT "ORDER_DETAIL_PROMOTION_ID_PROMOTION_ID_fk" FOREIGN KEY ("PROMOTION_ID") REFERENCES "public"."PROMOTION"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_STATUS_LOG" ADD CONSTRAINT "ORDER_STATUS_LOG_CUSTOMER_ORDER_ID_CUSTOMER_ORDER_ID_fk" FOREIGN KEY ("CUSTOMER_ORDER_ID") REFERENCES "public"."CUSTOMER_ORDER"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_STATUS_LOG" ADD CONSTRAINT "ORDER_STATUS_LOG_ORDER_STATUS_ID_ORDER_STATUS_ID_fk" FOREIGN KEY ("ORDER_STATUS_ID") REFERENCES "public"."ORDER_STATUS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_STATUS_LOG" ADD CONSTRAINT "ORDER_STATUS_LOG_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_CUSTOMER_ORDER_ID_CUSTOMER_ORDER_ID_fk" FOREIGN KEY ("CUSTOMER_ORDER_ID") REFERENCES "public"."CUSTOMER_ORDER"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_PAYMENT_TYPE_ID_PAYMENT_TYPE_ID_fk" FOREIGN KEY ("PAYMENT_TYPE_ID") REFERENCES "public"."PAYMENT_TYPE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_CURRENT_PAYMENT_STATUS_ID_PAYMENT_STATUS_ID_fk" FOREIGN KEY ("CURRENT_PAYMENT_STATUS_ID") REFERENCES "public"."PAYMENT_STATUS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT" ADD CONSTRAINT "PAYMENT_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT_STATUS_LOG" ADD CONSTRAINT "PAYMENT_STATUS_LOG_PAYMENT_ID_PAYMENT_ID_fk" FOREIGN KEY ("PAYMENT_ID") REFERENCES "public"."PAYMENT"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT_STATUS_LOG" ADD CONSTRAINT "PAYMENT_STATUS_LOG_PAYMENT_STATUS_ID_PAYMENT_STATUS_ID_fk" FOREIGN KEY ("PAYMENT_STATUS_ID") REFERENCES "public"."PAYMENT_STATUS"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PAYMENT_STATUS_LOG" ADD CONSTRAINT "PAYMENT_STATUS_LOG_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROMOTION" ADD CONSTRAINT "PROMOTION_PROMOTION_TYPE_ID_PROMOTION_TYPE_ID_fk" FOREIGN KEY ("PROMOTION_TYPE_ID") REFERENCES "public"."PROMOTION_TYPE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROMOTION" ADD CONSTRAINT "PROMOTION_CREATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("CREATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROMOTION" ADD CONSTRAINT "PROMOTION_UPDATED_BY_EMPLOYEE_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."EMPLOYEE"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROMOTION_FOOD" ADD CONSTRAINT "PROMOTION_FOOD_PROMOTION_ID_PROMOTION_ID_fk" FOREIGN KEY ("PROMOTION_ID") REFERENCES "public"."PROMOTION"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "PROMOTION_FOOD" ADD CONSTRAINT "PROMOTION_FOOD_FOOD_MENU_ID_FOOD_MENU_ID_fk" FOREIGN KEY ("FOOD_MENU_ID") REFERENCES "public"."FOOD_MENU"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "DISCOUNT_RULE" ADD CONSTRAINT "DISCOUNT_RULE_PROMOTION_ID_PROMOTION_ID_fk" FOREIGN KEY ("PROMOTION_ID") REFERENCES "public"."PROMOTION"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "BUY_X_GET_Y_RULE" ADD CONSTRAINT "BUY_X_GET_Y_RULE_PROMOTION_ID_PROMOTION_ID_fk" FOREIGN KEY ("PROMOTION_ID") REFERENCES "public"."PROMOTION"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "BUY_X_GET_Y_RULE" ADD CONSTRAINT "BUY_X_GET_Y_RULE_BUY_FOOD_ID_FOOD_MENU_ID_fk" FOREIGN KEY ("BUY_FOOD_ID") REFERENCES "public"."FOOD_MENU"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "BUY_X_GET_Y_RULE" ADD CONSTRAINT "BUY_X_GET_Y_RULE_FREE_FOOD_ID_FOOD_MENU_ID_fk" FOREIGN KEY ("FREE_FOOD_ID") REFERENCES "public"."FOOD_MENU"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_TABLE_ASSIGNMENT" ADD CONSTRAINT "ORDER_TABLE_ASSIGNMENT_CUSTOMER_ORDER_ID_CUSTOMER_ORDER_ID_fk" FOREIGN KEY ("CUSTOMER_ORDER_ID") REFERENCES "public"."CUSTOMER_ORDER"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ORDER_TABLE_ASSIGNMENT" ADD CONSTRAINT "ORDER_TABLE_ASSIGNMENT_RESTAURANT_TABLE_ID_RESTAURANT_TABLE_ID_fk" FOREIGN KEY ("RESTAURANT_TABLE_ID") REFERENCES "public"."RESTAURANT_TABLE"("ID") ON DELETE no action ON UPDATE no action;